<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cp3model" nsURI="http://inf.mit.bme.hu/donat/incquery-deps/cp1model"
    nsPrefix="cp3">
  <eClassifiers xsi:type="ecore:EClass" name="CP3StElem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sig" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ch" upperBound="-1" eType="#//CP3StElem"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CP3Dep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//CP3StElem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//CP3StElem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CP2Repo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deps" upperBound="-1" eType="#//CP3Dep"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elems" upperBound="-1"
        eType="#//CP3StElem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Types">
    <eLiterals name="Project" value="1"/>
    <eLiterals name="Class" value="2"/>
    <eLiterals name="Method" value="3"/>
    <eLiterals name="Field" value="4"/>
  </eClassifiers>
</ecore:EPackage>
